export const FETCH_TAGS_REQUEST = "FETCH_TAGS_REQUEST";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAILURE = "FETCH_TAGS_FAILURE";

export const CREATE_TAGS_REQUEST = "CREATE_TAGS_REQUEST";
export const CREATE_TAGS_SUCCESS = "CREATE_TAGS_SUCCESS";
export const CREATE_TAGS_FAILURE = "CREATE_TAGS_FAILURE";

export const UPDATE_TAGS_REQUEST = "UPDATE_TAGS_REQUEST";
export const UPDATE_TAGS_SUCCESS = "UPDATE_TAGS_SUCCESS";
export const UPDATE_TAGS_FAILURE = "UPDATE_TAGS_FAILURE";

export const DELETE_TAGS_REQUEST = "DELETE_TAGS_REQUEST";
export const DELETE_TAGS_SUCCESS = "DELETE_TAGS_SUCCESS";
export const DELETE_TAGS_FAILURE = "DELETE_TAGS_FAILURE";
